GET http://localhost:3000/user-api/users
###
POST http://localhost:3000/user-api/users 
Content-Type: application/json

{
    "id": 100,
    "name": "vikas",
    "age" : 19
}
###
PUT http://127.0.0.1:3000/user-api/users/100
Content-Type: application/json

{
    "id": 200,
    "name": "vikas",
    "age" : 20
}

###get request
GET http://localhost:3000/user-api/users/100


###
DELETE http://localhost:3000/user-api/users/200

### get all products
GET http://localhost:3000/product-api/products

### get product by id
GET http://localhost:3000/product-api/product-id/1001

### get product by name
GET http://localhost:3000/product-api/products-name/biryani

### create product
POST http://localhost:3000/product-api/products
Content-Type: application/json

{
  "productId": 1001,
  "productname": "biryani",
  "price": 120,
  "brand": "dum"
}

### update product
PUT http://localhost:3000/product-api/products/1001
Content-Type: application/json

{
  "productId": 1001,
  "productname": "fullmeals",
  "price": 220,
  "brand": "veg"
}

### delete product
DELETE http://localhost:3000/product-api/products/1001
